# Generated by Django 6.0.2 on 2026-02-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20260220_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='member_ship',
            new_name='membership',
        ),
    ]
